when:
  - event: push
    branch: main

skip_clone: true
steps:
  - name: test
    image: docker.io/library/debian:13
    commands:
      - echo "Resolv.conf:"
      - cat /etc/resolv.conf
      - id
      - apt update -y
      - apt install curl -y
      - curl https://github.com --verbose
  - name: build
    image: docker.io/library/debian:13
    commands:
      - echo "This is the build step"
      - 'printf ''#!/bin/sh\necho binary-data-123\n'' > executable'
      - chmod +x executable

  - name: a-test-step
    image: docker.io/library/golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable
