when:
  - event: push
    branch: main

steps:
  - name: build
    image: debian
    commands:
      - echo "This is the build step"
      - 'printf ''#!/bin/sh\necho binary-data-123\n'' > executable'
      - chmod +x executable

  - name: a-test-step
    image: golang:1.16
    commands:
      - echo "Testing ..."
      - ./executable
